[general]
import = ["C:\\Users\\igrif\\AppData\\Roaming\\alacritty\\themes\\themes\\enfocado_dark.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.7
startup_mode = "Maximized"

[window.padding]
x = 30
y = 30

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command"

[terminal.shell]
program = "wsl"
args = [
    "-d",
    "Debian",
    "--cd",
    "~"
]
